[project]
name = "browser-recall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "crawl4ai",
    "fastapi",
    "uvicorn[standard]",
    "crawl4ai",
    "browser-history",
    "python-dotenv"
]
