# Domains that should be ignored by the history tracker
# Supports wildcards (*) for pattern matching
ignored_domains:
  - "192.168.*" # Ignore local network addresses
  - "127.0.0.1" # Ignore localhost IP addresses
  - "localhost" # Ignore localhost domains
  - "172.*"
  - "localhost:*" # Ignore all localhost ports
  - "127.0.0.1:*" # Ignore all localhost IP ports
  - "*.local" # Ignore .local domains
  - "about:*" # Ignore about: URLs
  - "chrome-extension://*" # Ignore Chrome extensions
  - "chrome://*" # Ignore Chrome URLs
