# Domains to exclude from content reading
excluded_domains:
  - "identity.getpostman.com"
  - "localhost"
  - "127.0.0.1"
  - "namecheap.com"
  - "us.ovhcloud.com"
  - "linode.com"
  - "github.com/settings"
  - "secure.backblaze.com"
  - "login."
  - "identity."
  - ".auth."
  - "192.168."
  - "172.16."
  - "0.0.0."
