# Domains to exclude from content reading
excluded_domains:
  - "identity.getpostman.com"
  - "localhost"
  - "127.0.0.1"
  - "ap.www.namecheap.com*"
  - "*.namecheap.com*"
  - "us.ovhcloud.com*"
  - "cloud.linode.com*"
  - "*.linode.com*"
  - "linode.com*"
  - "*.login.*"
  - "*.auth.*"
  - "192.168.*.*"
  - "10.*.*.*"
  - "172.16.*.*"
  - "0.0.0.*"
